[project]
name = "humanoid-robot-grasping"
version = "0.1.0"
description = "Initial plush object tracking utilities for Unitree G1 project."
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.9",
]

[project.optional-dependencies]
loco = [
    "unitree-sdk2==1.0.1",
]

[dependency-groups]
dev = []

[project.scripts]
object-manual-tracker = "object_tracking.manual_tracker:main"
loco = "object_tracking.g1_loco_cli:main"
vision = "object_tracking.g1_vision_cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = true
