#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ROBOT_PYTHON="${ROBOT_PYTHON:-${ROOT_DIR}/robot/.venv/bin/python}"
NATIVE_ARM_PYTHON="${NATIVE_ARM_PYTHON:-${HOME}/Documents/repos/xr_teleoperate/.venv/bin/python}"
NATIVE_ARM_SOCKET="${NATIVE_ARM_SOCKET:-${XDG_RUNTIME_DIR:-/tmp}/g1-native-arm-${UID}.sock}"
CLIENT_IP="${CLIENT_IP:-${GB10_HOST:-192.168.0.66}}"
ROBOT_INTERFACE="${ROBOT_INTERFACE:-wlan0}"
HARDWARE_INTERFACE="${HARDWARE_INTERFACE:-eth0}"
UNITREE_CONTROL_PEER="${UNITREE_CONTROL_PEER:-192.168.123.1}"
# Keep standalone robot/GB10 launches on the same dedicated project domain.
# Domain 42 was used by older processes and caused silent split-brain launches
# when bunny-test used 43 while `robot start` retained this default.
ROS_DOMAIN_ID="${G1_PROJECT_ROS_DOMAIN_ID:-43}"
HARDWARE_DOMAIN_ID="${HARDWARE_DOMAIN_ID:-0}"
MAX_TILT_DEG="${MAX_TILT_DEG:-5}"
MAX_WAIST_DEVIATION_DEG="${MAX_WAIST_DEVIATION_DEG:-3}"
ARM_WEIGHT_RAMP_S="${ARM_WEIGHT_RAMP_S:-1.5}"
ARM_MAX_VELOCITY_RAD_S="${ARM_MAX_VELOCITY_RAD_S:-0.15}"
ARM_MAX_ACCELERATION_RAD_S2="${ARM_MAX_ACCELERATION_RAD_S2:-0.5}"
ARM_MAX_JERK_RAD_S3="${ARM_MAX_JERK_RAD_S3:-2.0}"
CALIBRATION="${CALIBRATION:-}"
RGB_MODE="${RGB_MODE:-unitree}"
ALLOW_MOVEMENT="${ALLOW_MOVEMENT:-0}"
EXPECTED_MOTION_MODE="${EXPECTED_MOTION_MODE:-}"
G1_ROBOT_ID="${G1_ROBOT_ID:-}"
# The robot's RealSense exposes depth directly but not a usable ROS-aligned
# RGB stream. Prefer that known-good source; operators can explicitly request
# --depth-source ros when an aligned sensor_msgs/Image pipeline is present.
DEPTH_SOURCE="${DEPTH_SOURCE:-librealsense}"
ROS_IMAGE_TOPIC="${ROS_IMAGE_TOPIC:-/camera/camera/depth/image_rect_raw}"
ROS_CAMERA_INFO_TOPIC="${ROS_CAMERA_INFO_TOPIC:-/camera/camera/depth/camera_info}"
ROS_DEPTH_SCALE="${ROS_DEPTH_SCALE:-0.001}"
DEPTH_WIDTH="${DEPTH_WIDTH:-848}"
DEPTH_HEIGHT="${DEPTH_HEIGHT:-480}"
DEPTH_CAPTURE_FPS="${DEPTH_CAPTURE_FPS:-60}"
# Capture at the sensor rate, but keep ROS transmission bounded. Converting a
# compressed 848x480 frame into the generated byte-sequence message at 60 Hz
# can outrun DDS and retain gigabytes of queued Python objects.
DEPTH_PUBLISH_FPS="${DEPTH_PUBLISH_FPS:-15}"
REALSENSE_RGB_PORT="${CLIENT_PORT:-5600}"
REALSENSE_RGB_FPS="${REALSENSE_RGB_FPS:-60}"
DEPTH_SERIAL="${DEPTH_SERIAL:-}"
DISABLE_DEPTH="${DISABLE_DEPTH:-0}"
QUIET_HEALTHY_DEPTH="${QUIET_HEALTHY_DEPTH:-0}"
CONTROL_MODE="tracking"
# The split tracking relay matches GB10's CycloneDDS RMW.  Native SDK2 owns a
# different CycloneDDS process and domain, so the two implementations no
# longer load into one interpreter.  Legacy combined modes retain Fast DDS.
if [[ "${CONTROL_MODE}" == "tracking" ]]; then
  export RMW_IMPLEMENTATION="${G1_ARM_RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}"
else
  export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
fi

if [[ -z "${CLIENT_IP}" ]]; then
  echo "CLIENT_IP (the GB10 address) is required." >&2
  exit 1
fi
if [[ ! -x "${ROBOT_PYTHON}" ]]; then
  echo "Missing robot environment. Run: uv run g1 setup robot" >&2
  exit 1
fi
if [[ "${CONTROL_MODE}" == "tracking" && ! -x "${NATIVE_ARM_PYTHON}" ]]; then
  echo "Missing XR Python 3.10 environment: ${NATIVE_ARM_PYTHON}" >&2
  exit 1
fi
if [[ "${ALLOW_MOVEMENT}" == "1" && -z "${EXPECTED_MOTION_MODE}" ]]; then
  echo "EXPECTED_MOTION_MODE is required when ALLOW_MOVEMENT=1." >&2
  exit 1
fi
pids=()
cleanup() {
  local pid
  for pid in "${pids[@]:-}"; do
    kill -TERM "${pid}" 2>/dev/null || true
  done
  # Camera and DDS children may need a moment to unwind C/C++ callbacks.
  # Wait before escalating so RealSense file descriptors are actually closed
  # and the next foreground test does not fail with VIDIOC_S_FMT EBUSY.
  local attempt
  for attempt in {1..30}; do
    local alive=0
    for pid in "${pids[@]:-}"; do
      if kill -0 "${pid}" 2>/dev/null; then
        alive=1
        break
      fi
    done
    [[ "${alive}" == "0" ]] && break
    sleep 0.1
  done
  for pid in "${pids[@]:-}"; do
    if kill -0 "${pid}" 2>/dev/null; then
      kill -KILL "${pid}" 2>/dev/null || true
    fi
  done
  wait "${pids[@]:-}" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# Start native DDS before sourcing Foxy.  This child gets only the project
# package path and XR's Python 3.10 environment; it never imports rclpy or any
# ROS-generated type support.
if [[ "${CONTROL_MODE}" == "tracking" ]]; then
  native_args=(
    --socket "${NATIVE_ARM_SOCKET}"
    --hardware-interface "${HARDWARE_INTERFACE}"
    --hardware-domain-id "${HARDWARE_DOMAIN_ID}"
    --max-tilt-deg "${MAX_TILT_DEG}"
    --max-waist-deviation-deg "${MAX_WAIST_DEVIATION_DEG}"
    --weight-ramp-s "${ARM_WEIGHT_RAMP_S}"
    --max-velocity-rad-s "${ARM_MAX_VELOCITY_RAD_S}"
    --max-acceleration-rad-s2 "${ARM_MAX_ACCELERATION_RAD_S2}"
    --max-jerk-rad-s3 "${ARM_MAX_JERK_RAD_S3}"
  )
  if [[ -n "${CALIBRATION}" ]]; then
    native_args+=(--calibration "${CALIBRATION}")
  fi
  if [[ "${ALLOW_MOVEMENT}" == "1" ]]; then
    native_args+=(--allow-movement --expected-motion-mode "${EXPECTED_MOTION_MODE}")
  fi
  env \
    -u AMENT_PREFIX_PATH \
    -u COLCON_PREFIX_PATH \
    -u ROS_DISTRO \
    -u ROS_DOMAIN_ID \
    -u RMW_IMPLEMENTATION \
    -u FASTRTPS_DEFAULT_PROFILES_FILE \
    -u FASTDDS_DEFAULT_PROFILES_FILE \
    -u CYCLONEDDS_URI \
    PYTHONPATH="${ROOT_DIR}/src" \
    LD_LIBRARY_PATH="${UNITREE_SDK_DDS_LIBRARY_DIR:-/usr/local/lib}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" \
    "${NATIVE_ARM_PYTHON}" "${ROOT_DIR}/scripts/robot/native_arm_worker.py" \
    "${native_args[@]}" &
  pids+=("$!")
  native_pid="$!"
  for _ in {1..100}; do
    [[ -S "${NATIVE_ARM_SOCKET}" ]] && break
    if ! kill -0 "${native_pid}" 2>/dev/null; then
      echo "Native arm worker exited during startup." >&2
      exit 1
    fi
    sleep 0.05
  done
  if [[ ! -S "${NATIVE_ARM_SOCKET}" ]]; then
    echo "Native arm worker did not create ${NATIVE_ARM_SOCKET}." >&2
    exit 1
  fi
fi

source "${ROOT_DIR}/scripts/shared/ros-env.sh"
g1_source_ros "${ROOT_DIR}" foxy
g1_configure_cyclonedds \
  robot "${ROBOT_INTERFACE}" "${CLIENT_IP},${UNITREE_CONTROL_PEER}" "${ROS_DOMAIN_ID}"
pkill -TERM -u "$(id -u)" -f \
  "[r]os2cli.daemon.daemonize.*--ros-domain-id ${ROS_DOMAIN_ID}" 2>/dev/null || true
export ROS2CLI_NO_DAEMON=1

export PYTHONPATH="${ROOT_DIR}:${ROOT_DIR}/src${PYTHONPATH:+:${PYTHONPATH}}"

node_args=(
  --control-mode "${CONTROL_MODE}"
  --manual-control-profile "${MANUAL_ARM_PROFILE:-xr}"
  --depth-source "${DEPTH_SOURCE}"
  --ros-image-topic "${ROS_IMAGE_TOPIC}"
  --ros-camera-info-topic "${ROS_CAMERA_INFO_TOPIC}"
  --ros-depth-scale "${ROS_DEPTH_SCALE}"
  --depth-width "${DEPTH_WIDTH}"
  --depth-height "${DEPTH_HEIGHT}"
  --depth-capture-fps "${DEPTH_CAPTURE_FPS}"
  --depth-publish-fps "${DEPTH_PUBLISH_FPS}"
  --hardware-interface "${HARDWARE_INTERFACE}"
  --hardware-domain-id "${HARDWARE_DOMAIN_ID}"
)
if [[ -n "${CALIBRATION}" ]]; then
  node_args+=(--calibration "${CALIBRATION}")
fi
if [[ -n "${G1_ROBOT_ID}" ]]; then
  node_args+=(--robot-id "${G1_ROBOT_ID}")
fi
if [[ -n "${DEPTH_SERIAL}" ]]; then
  node_args+=(--depth-serial "${DEPTH_SERIAL}")
fi
if [[ "${DISABLE_DEPTH}" == "1" ]]; then
  node_args+=(--disable-depth)
fi
if [[ "${ALLOW_MOVEMENT}" == "1" ]]; then
  node_args+=(--allow-movement --expected-motion-mode "${EXPECTED_MOTION_MODE}")
fi
if [[ "${RGB_MODE}" == "realsense" ]]; then
  node_args+=(
    --realsense-rgb-target "${CLIENT_IP}"
    --realsense-rgb-port "${REALSENSE_RGB_PORT}"
    --realsense-rgb-fps "${REALSENSE_RGB_FPS}"
  )
fi

case "${RGB_MODE}" in
  unitree)
    ROBOT_INTERFACE="${HARDWARE_INTERFACE}" CLIENT_IP="${CLIENT_IP}" "${ROOT_DIR}/scripts/robot/rgb-relay.sh" &
    pids+=("$!")
    ;;
  30fps)
    ROBOT_INTERFACE="${HARDWARE_INTERFACE}" "${ROOT_DIR}/scripts/robot/rgb-30fps.sh" &
    pids+=("$!")
    ALLOW_EXTERNAL_RGB_SOURCE=1 ROBOT_INTERFACE="${HARDWARE_INTERFACE}" CLIENT_IP="${CLIENT_IP}" \
      "${ROOT_DIR}/scripts/robot/rgb-relay.sh" &
    pids+=("$!")
    ;;
  highfps-service)
    ROBOT_INTERFACE="${HARDWARE_INTERFACE}" CLIENT_IP="${CLIENT_IP}" \
      "${ROOT_DIR}/scripts/robot/rgb-relay.sh" &
    pids+=("$!")
    ;;
  realsense)
    echo "D435I RGB and RGB-aligned depth will be captured together at ${REALSENSE_RGB_FPS} FPS."
    ;;
  *)
    echo "RGB_MODE must be unitree, 30fps, highfps-service, or realsense, got: ${RGB_MODE}" >&2
    exit 2
    ;;
esac

if [[ "${CONTROL_MODE}" == "tracking" ]]; then
  "${ROBOT_PYTHON}" "${ROOT_DIR}/scripts/robot/arm_ros_relay.py" \
    --socket "${NATIVE_ARM_SOCKET}" &
  pids+=("$!")
  if [[ "${DISABLE_DEPTH}" != "1" ]]; then
    depth_args=(
      --depth-only
      --depth-source "${DEPTH_SOURCE}"
      --ros-image-topic "${ROS_IMAGE_TOPIC}"
      --ros-camera-info-topic "${ROS_CAMERA_INFO_TOPIC}"
      --ros-depth-scale "${ROS_DEPTH_SCALE}"
      --depth-width "${DEPTH_WIDTH}"
      --depth-height "${DEPTH_HEIGHT}"
      --depth-capture-fps "${DEPTH_CAPTURE_FPS}"
      --depth-publish-fps "${DEPTH_PUBLISH_FPS}"
      --depth-tcp-target "${CLIENT_IP}"
      --depth-tcp-port "${DEPTH_TCP_PORT:-5601}"
    )
    if [[ -n "${CALIBRATION}" ]]; then
      depth_args+=(--calibration "${CALIBRATION}")
    fi
    if [[ -n "${DEPTH_SERIAL}" ]]; then
      depth_args+=(--depth-serial "${DEPTH_SERIAL}")
    fi
    if [[ "${RGB_MODE}" == "realsense" ]]; then
      depth_args+=(
        --realsense-rgb-target "${CLIENT_IP}"
        --realsense-rgb-port "${REALSENSE_RGB_PORT}"
        --realsense-rgb-fps "${REALSENSE_RGB_FPS}"
      )
    fi
    if [[ "${QUIET_HEALTHY_DEPTH}" == "1" ]]; then
      depth_args+=(--quiet-healthy-depth)
    fi
    "${ROBOT_PYTHON}" "${ROOT_DIR}/scripts/robot/ros_node.py" "${depth_args[@]}" &
    pids+=("$!")
  fi
else
  "${ROBOT_PYTHON}" "${ROOT_DIR}/scripts/robot/ros_node.py" "${node_args[@]}" &
  pids+=("$!")
fi

echo "Robot ROS 2 node started control_mode=${CONTROL_MODE} movement_permitted=${ALLOW_MOVEMENT} initial_state=DISARMED."
if [[ "${CONTROL_MODE}" == "tracking" ]]; then
  echo "Arm transport split: XR Python native worker ${NATIVE_ARM_SOCKET}; Foxy ROS JSON relay."
fi
echo "ROS domain ${ROS_DOMAIN_ID}; interface ${ROBOT_INTERFACE}; static peers ${CLIENT_IP}, ${UNITREE_CONTROL_PEER}."
echo "RGB remains RTP/UDP ${CLIENT_IP}:${CLIENT_PORT:-5600}; the robot exposes no HTTP server."
wait -n "${pids[@]}"
echo "A robot process exited; stopping the process group." >&2
exit 1
